## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

## 2. Load the Datasets

In [2]:
games_details = pd.read_csv("../data/raw/games_details.csv")
games = pd.read_csv("../data/raw/games.csv")
players = pd.read_csv("../data/raw/players.csv")
ranking = pd.read_csv("../data/raw/ranking.csv")
teams = pd.read_csv("../data/raw/teams.csv")

C:\Users\JB MADHUBALA\AppData\Local\Temp\ipykernel_29760\4210556289.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  games_details = pd.read_csv("../data/raw/games_details.csv")

In [3]:
games_details.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,7.0,14.0,0.500,2.0,4.0,0.500,7.0,10.0,0.7,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,6.0,9.0,0.667,0.0,0.0,0.000,1.0,1.0,1.0,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,4.0,13.0,0.308,1.0,6.0,0.167,1.0,1.0,1.0,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,7.0,12.0,0.583,1.0,3.0,0.333,4.0,4.0,1.0,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0

In [4]:
games.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,0.382,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,0.457,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,0.313,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,0.297,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,0.378,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0

In [5]:
players.head()

        PLAYER_NAME     TEAM_ID  PLAYER_ID  SEASON
0     Royce O'Neale  1610612762    1626220    2019
1  Bojan Bogdanovic  1610612762     202711    2019
2       Rudy Gobert  1610612762     203497    2019
3  Donovan Mitchell  1610612762    1628378    2019
4       Mike Conley  1610612762     201144    2019

In [6]:
ranking.head()

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN

In [7]:
teams.head()

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends

## 4. Understand Dataset Shape & Info

In [8]:
print("Game Details:", games_details.shape)
print("Games:", games.shape)
print("Players:", players.shape)
print("Ranking:", ranking.shape)
print("Teams:", teams.shape)

Game Details: (668628, 29)
Games: (26651, 21)
Players: (7228, 4)
Ranking: (210342, 13)
Teams: (30, 14)

In [9]:
games_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668628 entries, 0 to 668627
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   GAME_ID            668628 non-null  int64
 1   TEAM_ID            668628 non-null  int64
 2   TEAM_ABBREVIATION  668628 non-null  object
 3   TEAM_CITY          668628 non-null  object
 4   PLAYER_ID          668628 non-null  int64
 5   PLAYER_NAME        668628 non-null  object
 6   NICKNAME           53037 non-null   object
 7   START_POSITION     255765 non-null  object
 8   COMMENT            109689 non-null  object
 9   MIN                558938 non-null  object
 10  FGM                558938 non-null  float64
 11  FGA                558938 non-null  float64
 12  FG_PCT             558938 non-null  float64
 13  FG3M               558938 non-null  float64
 14  FG3A               558938 non-null  float64
 15  FG3_PCT            558938 non-null  float64
 16  FTM                558938 non-null  float64
 17  FTA                558938 non-null  float64
 18  FT_PCT             558938 non-null  float64
 19  OREB               558938 non-null  float64
 20  DREB               558938 non-null  float64
 21  REB                558938 non-null  float64
 22  AST                558938 non-null  float64
 23  STL                558938 non-null  float64
 24  BLK                558938 non-null  float64
 25  TO                 558938 non-null  float64
 26  PF                 558938 non-null  float64
 27  PTS                558938 non-null  float64
 28  PLUS_MINUS         535277 non-null  float64
dtypes: float64(19), int64(3), object(7)
memory usage: 147.9+ MB

In [10]:
# Check unique formats
games_details['MIN'].dropna().head(10)

0    18:06
1    31:01
2    21:42
3    30:20
4    27:44
5    18:04
6    16:55
7    21:20
8    21:10
9     9:16
Name: MIN, dtype: object

In [11]:
games_details_cleaned = games_details.copy()

def convert_min_to_float(min_str):
    if isinstance(min_str, str) and ':' in min_str:
        minutes, seconds = min_str.split(':')
        return float(minutes) + float(seconds)/60
    try:
        return float(min_str)
    except:
        return np.nan
games_details_cleaned['MIN_PLAYED'] = games_details['MIN'].apply(convert_min_to_float)

In [12]:
games_details_cleaned = games_details_cleaned[games_details_cleaned['MIN_PLAYED'] > 0]

In [13]:
games_details_cleaned['PLUS_MINUS'] = games_details_cleaned['PLUS_MINUS'].fillna(0)

In [14]:
games_details_cleaned['START_POSITION'] = games_details_cleaned['START_POSITION'].fillna('Bench')

In [15]:
games_details_cleaned['COMMENT'] = games_details_cleaned['COMMENT'].fillna('No Comment')

In [16]:
games_details_cleaned['NICKNAME'] = games_details_cleaned['NICKNAME'].fillna('NA')

In [17]:
games_details_cleaned.rename(columns={
    'PLAYER_NAME': 'Player',
    'TEAM_ABBREVIATION': 'Team',
    'PTS': 'Points'
}, inplace=True)

In [18]:
games_details_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 558746 entries, 0 to 668627
Data columns (total 30 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   GAME_ID         558746 non-null  int64
 1   TEAM_ID         558746 non-null  int64
 2   Team            558746 non-null  object
 3   TEAM_CITY       558746 non-null  object
 4   PLAYER_ID       558746 non-null  int64
 5   Player          558746 non-null  object
 6   NICKNAME        558746 non-null  object
 7   START_POSITION  558746 non-null  object
 8   COMMENT         558746 non-null  object
 9   MIN             558746 non-null  object
 10  FGM             558746 non-null  float64
 11  FGA             558746 non-null  float64
 12  FG_PCT          558746 non-null  float64
 13  FG3M            558746 non-null  float64
 14  FG3A            558746 non-null  float64
 15  FG3_PCT         558746 non-null  float64
 16  FTM             558746 non-null  float64
 17  FTA             558746 non-null  float64
 18  FT_PCT          558746 non-null  float64
 19  OREB            558746 non-null  float64
 20  DREB            558746 non-null  float64
 21  REB             558746 non-null  float64
 22  AST             558746 non-null  float64
 23  STL             558746 non-null  float64
 24  BLK             558746 non-null  float64
 25  TO              558746 non-null  float64
 26  PF              558746 non-null  float64
 27  Points          558746 non-null  float64
 28  PLUS_MINUS      558746 non-null  float64
 29  MIN_PLAYED      558746 non-null  float64
dtypes: float64(20), int64(3), object(7)
memory usage: 132.1+ MB

In [19]:
(games_details_cleaned[['Points','FGA','AST','REB']] < 0).sum()

Points    0
FGA       0
AST       0
REB       0
dtype: int64

In [20]:
games_details_cleaned['MIN_PLAYED'].describe()

count    558746.000000
mean         22.917167
std          11.228932
min           0.016667
25%          14.633333
50%          23.350000
75%          31.800000
max          96.000000
Name: MIN_PLAYED, dtype: float64

In [21]:
games_details_cleaned.to_csv("../data/processed/games_details_cleaned.csv", index=False)

In [22]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26651 entries, 0 to 26650
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26651 non-null  object
 1   GAME_ID           26651 non-null  int64
 2   GAME_STATUS_TEXT  26651 non-null  object
 3   HOME_TEAM_ID      26651 non-null  int64
 4   VISITOR_TEAM_ID   26651 non-null  int64
 5   SEASON            26651 non-null  int64
 6   TEAM_ID_home      26651 non-null  int64
 7   PTS_home          26552 non-null  float64
 8   FG_PCT_home       26552 non-null  float64
 9   FT_PCT_home       26552 non-null  float64
 10  FG3_PCT_home      26552 non-null  float64
 11  AST_home          26552 non-null  float64
 12  REB_home          26552 non-null  float64
 13  TEAM_ID_away      26651 non-null  int64
 14  PTS_away          26552 non-null  float64
 15  FG_PCT_away       26552 non-null  float64
 16  FT_PCT_away       26552 non-null  float64
 17  FG3_PCT_away      26552 non-null  float64
 18  AST_away          26552 non-null  float64
 19  REB_away          26552 non-null  float64
 20  HOME_TEAM_WINS    26651 non-null  int64
dtypes: float64(12), int64(7), object(2)
memory usage: 4.3+ MB

In [23]:
games_cleaned = games.copy()
games['GAME_DATE_EST'] = pd.to_datetime(games['GAME_DATE_EST'])

In [24]:
games['GAME_STATUS_TEXT'].value_counts()

GAME_STATUS_TEXT
Final    26651
Name: count, dtype: int64

In [25]:
games.isnull().sum()

GAME_DATE_EST        0
GAME_ID              0
GAME_STATUS_TEXT     0
HOME_TEAM_ID         0
VISITOR_TEAM_ID      0
SEASON               0
TEAM_ID_home         0
PTS_home            99
FG_PCT_home         99
FT_PCT_home         99
FG3_PCT_home        99
AST_home            99
REB_home            99
TEAM_ID_away         0
PTS_away            99
FG_PCT_away         99
FT_PCT_away         99
FG3_PCT_away        99
AST_away            99
REB_away            99
HOME_TEAM_WINS       0
dtype: int64

In [26]:
games_cleaned = games_cleaned.dropna()

In [27]:
games_cleaned["SEASON"] = games_cleaned["SEASON"].astype(int)

In [28]:
games_cleaned['GAME_RESULT'] = np.where(
    games_cleaned['HOME_TEAM_WINS'] == 1,
    'HOME_WIN',
    'AWAY_WIN'
)

games_cleaned["GAME_RESULT"] = (
    games_cleaned["GAME_RESULT"]
    .str.strip()
    .str.upper()
    .str.replace(" ", "_")
)

In [29]:
games_cleaned['TOTAL_POINTS'] = games_cleaned['PTS_home'] + games_cleaned['PTS_away']

In [30]:
games_cleaned["GAME_STATUS_TEXT"] = games_cleaned["GAME_STATUS_TEXT"].astype("category")

In [31]:
games_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26552 entries, 0 to 26650
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26552 non-null  object
 1   GAME_ID           26552 non-null  int64
 2   GAME_STATUS_TEXT  26552 non-null  category
 3   HOME_TEAM_ID      26552 non-null  int64
 4   VISITOR_TEAM_ID   26552 non-null  int64
 5   SEASON            26552 non-null  int32
 6   TEAM_ID_home      26552 non-null  int64
 7   PTS_home          26552 non-null  float64
 8   FG_PCT_home       26552 non-null  float64
 9   FT_PCT_home       26552 non-null  float64
 10  FG3_PCT_home      26552 non-null  float64
 11  AST_home          26552 non-null  float64
 12  REB_home          26552 non-null  float64
 13  TEAM_ID_away      26552 non-null  int64
 14  PTS_away          26552 non-null  float64
 15  FG_PCT_away       26552 non-null  float64
 16  FT_PCT_away       26552 non-null  float64
 17  FG3_PCT_away      26552 non-null  float64
 18  AST_away          26552 non-null  float64
 19  REB_away          26552 non-null  float64
 20  HOME_TEAM_WINS    26552 non-null  int64
 21  GAME_RESULT       26552 non-null  object
 22  TOTAL_POINTS      26552 non-null  float64
dtypes: category(1), float64(13), int32(1), int64(6), object(2)
memory usage: 4.6+ MB

In [32]:
games_cleaned.to_csv("../data/processed/games_cleaned.csv", index=False)

In [33]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7228 entries, 0 to 7227
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PLAYER_NAME  7228 non-null   object
 1   TEAM_ID      7228 non-null   int64
 2   PLAYER_ID    7228 non-null   int64
 3   SEASON       7228 non-null   int64
dtypes: int64(3), object(1)
memory usage: 226.0+ KB

In [34]:
players.to_csv("../data/processed/players_cleaned.csv", index=False)

In [35]:
ranking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210342 entries, 0 to 210341
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TEAM_ID        210342 non-null  int64
 1   LEAGUE_ID      210342 non-null  int64
 2   SEASON_ID      210342 non-null  int64
 3   STANDINGSDATE  210342 non-null  object
 4   CONFERENCE     210342 non-null  object
 5   TEAM           210342 non-null  object
 6   G              210342 non-null  int64
 7   W              210342 non-null  int64
 8   L              210342 non-null  int64
 9   W_PCT          210342 non-null  float64
 10  HOME_RECORD    210342 non-null  object
 11  ROAD_RECORD    210342 non-null  object
 12  RETURNTOPLAY   3990 non-null    float64
dtypes: float64(2), int64(6), object(5)
memory usage: 20.9+ MB

In [36]:
ranking_cleaned = ranking.copy()

ranking_cleaned["RETURNTOPLAY"] = ranking_cleaned["RETURNTOPLAY"].fillna(0)

In [37]:
ranking_cleaned["STANDINGSDATE"] = pd.to_datetime(ranking_cleaned["STANDINGSDATE"])

In [38]:
ranking_cleaned[["HOME_WINS", "HOME_LOSSES"]] = ranking_cleaned["HOME_RECORD"].str.split("-", expand=True).astype(int)
ranking_cleaned[["ROAD_WINS", "ROAD_LOSSES"]] = ranking_cleaned["ROAD_RECORD"].str.split("-", expand=True).astype(int)

In [39]:
ranking_cleaned["SEASON_YEAR"] = ranking_cleaned["SEASON_ID"] % 10000
ranking_cleaned["SEASON_PHASE"] = ranking_cleaned["SEASON_ID"] // 10000

In [40]:
ranking_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210342 entries, 0 to 210341
Data columns (total 19 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TEAM_ID        210342 non-null  int64
 1   LEAGUE_ID      210342 non-null  int64
 2   SEASON_ID      210342 non-null  int64
 3   STANDINGSDATE  210342 non-null  datetime64[ns]
 4   CONFERENCE     210342 non-null  object
 5   TEAM           210342 non-null  object
 6   G              210342 non-null  int64
 7   W              210342 non-null  int64
 8   L              210342 non-null  int64
 9   W_PCT          210342 non-null  float64
 10  HOME_RECORD    210342 non-null  object
 11  ROAD_RECORD    210342 non-null  object
 12  RETURNTOPLAY   210342 non-null  float64
 13  HOME_WINS      210342 non-null  int32
 14  HOME_LOSSES    210342 non-null  int32
 15  ROAD_WINS      210342 non-null  int32
 16  ROAD_LOSSES    210342 non-null  int32
 17  SEASON_YEAR    210342 non-null  int64
 18  SEASON_PHASE   210342 non-null  int64
dtypes: datetime64[ns](1), float64(2), int32(4), int64(8), object(4)
memory usage: 27.3+ MB

In [41]:
ranking_cleaned.to_csv("../data/processed/ranking_cleaned.csv", index=False)

In [42]:
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   LEAGUE_ID           30 non-null     int64
 1   TEAM_ID             30 non-null     int64
 2   MIN_YEAR            30 non-null     int64
 3   MAX_YEAR            30 non-null     int64
 4   ABBREVIATION        30 non-null     object
 5   NICKNAME            30 non-null     object
 6   YEARFOUNDED         30 non-null     int64
 7   CITY                30 non-null     object
 8   ARENA               30 non-null     object
 9   ARENACAPACITY       26 non-null     float64
 10  OWNER               30 non-null     object
 11  GENERALMANAGER      30 non-null     object
 12  HEADCOACH           30 non-null     object
 13  DLEAGUEAFFILIATION  30 non-null     object
dtypes: float64(1), int64(5), object(8)
memory usage: 3.4+ KB

In [43]:
games_with_teams = games_cleaned.merge(
    teams,
    left_on="HOME_TEAM_ID",
    right_on="TEAM_ID",
    how="left"
).rename(columns={
    "CITY": "HOME_CITY",
    "NICKNAME": "HOME_TEAM_NAME"
}).drop(columns=["TEAM_ID"])

In [44]:
games_with_teams = games_with_teams.merge(
    teams,
    left_on="VISITOR_TEAM_ID",
    right_on="TEAM_ID",
    how="left"
).rename(columns={
    "CITY": "AWAY_CITY",
    "NICKNAME": "AWAY_TEAM_NAME"
}).drop(columns=["TEAM_ID"])

In [45]:
teams.to_csv("../data/processed/teams_cleaned.csv", index=False)

In [46]:
games_with_teams.to_csv(
    "../data/processed/games_with_teams.csv",
    index=False
)